<script>

</script>

<template>
     <v-app> 
      <v-app-bar app color="deep-purple darken-2">
        <v-container max-width="xl" class="py-4">
          <v-row>
            <v-col cols="12">
              <h1 class="display-1 font-weight-bold white--text">
                Administrador de Libros
              </h1>
            </v-col>
          </v-row>
        </v-container>
      </v-app-bar>
      <v-main class="pa-5">
        <v-container max-width="960px" class="mt-10">
          <v-row>
            <v-col>
              <h1 class="display-1 font-weight-bold">Agregar Libro</h1> 
            </v-col>
          </v-row>
        </v-container>
      </v-main>
    </v-app>
</template>